name: fizzybutton
description: A fizzy animated login button with bubble effects and smooth loading transition.
version: 0.0.1
homepage: https://github.com/txngerine/fizzybutton
repository: https://github.com/txngerine/fizzybutton
issue_tracker: https://github.com/txngerine/fizzybutton/issues

license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: